name: Docker Build and Push Workflow

on:
  push:
    branches:
      - production
    paths-ignore:
      - .github/workflows/docker-build-push.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        id: build
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/browser-elaunch:latest .

      - name: List Docker Images
        run: |
          docker images  # This will display all local Docker images for debugging

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/browser-elaunch:latest
